-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 07:45:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_pruebaac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pruebaac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pruebaac` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `db_pruebaac` ;

-- -----------------------------------------------------
-- Table `db_pruebaac`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pruebaac`.`region` (
  `idregion` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idregion`),
  UNIQUE INDEX `idregion_UNIQUE` (`idregion` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `db_pruebaac`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pruebaac`.`state` (
  `idstate` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `abbreviation` VARCHAR(2) NOT NULL,
  `phoneareacode` INT(3) NOT NULL,
  `regionID` INT(11) NOT NULL,
  PRIMARY KEY (`idstate`),
  UNIQUE INDEX `idstate_UNIQUE` (`idstate` ASC) ,
  INDEX `regionID_idx` (`regionID` ASC),
  CONSTRAINT `regionID`
    FOREIGN KEY (`regionID`)
    REFERENCES `db_pruebaac`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `db_pruebaac`.`county`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pruebaac`.`county` (
  `idcounty` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `stateID` INT(11) NOT NULL,
  PRIMARY KEY (`idcounty`),
  UNIQUE INDEX `idcounty_UNIQUE` (`idcounty` ASC),
  INDEX `stateID_idx` (`stateID` ASC),
  CONSTRAINT `stateID`
    FOREIGN KEY (`stateID`)
    REFERENCES `db_pruebaac`.`state` (`idstate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `db_pruebaac`.`placename`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pruebaac`.`placename` (
  `idplacename` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `postalcode` VARCHAR(5) NOT NULL,
  `countyID` INT(11) NOT NULL,
  PRIMARY KEY (`idplacename`),
  UNIQUE INDEX `idplacename_UNIQUE` (`idplacename` ASC) ,
  UNIQUE INDEX `postalcode_UNIQUE` (`postalcode` ASC),
  INDEX `countyID_idx` (`countyID` ASC),
  CONSTRAINT `countyID`
    FOREIGN KEY (`countyID`)
    REFERENCES `db_pruebaac`.`county` (`idcounty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;